
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND FALSE LPAREN NAME NOT OR RPAREN TRUE XOR\n    expression : NOT expression\n    expression : expression AND expression\n                  | expression OR expression\n                  | expression XOR expressionexpression : LPAREN expression RPARENexpression : NAMEexpression : TRUE\n                | FALSE'
    
_lr_action_items = {'NOT':([0,2,3,7,8,9,],[2,2,2,2,2,2,]),'LPAREN':([0,2,3,7,8,9,],[3,3,3,3,3,3,]),'NAME':([0,2,3,7,8,9,],[4,4,4,4,4,4,]),'TRUE':([0,2,3,7,8,9,],[5,5,5,5,5,5,]),'FALSE':([0,2,3,7,8,9,],[6,6,6,6,6,6,]),'$end':([1,4,5,6,10,12,13,14,15,],[0,-6,-7,-8,-1,-2,-3,-4,-5,]),'AND':([1,4,5,6,10,11,12,13,14,15,],[7,-6,-7,-8,7,7,7,7,7,-5,]),'OR':([1,4,5,6,10,11,12,13,14,15,],[8,-6,-7,-8,8,8,8,8,8,-5,]),'XOR':([1,4,5,6,10,11,12,13,14,15,],[9,-6,-7,-8,9,9,9,9,9,-5,]),'RPAREN':([4,5,6,10,11,12,13,14,15,],[-6,-7,-8,-1,15,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,7,8,9,],[1,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NOT expression','expression',2,'p_expression_not','booleanParser.py',77),
  ('expression -> expression AND expression','expression',3,'p_expression_binop','booleanParser.py',85),
  ('expression -> expression OR expression','expression',3,'p_expression_binop','booleanParser.py',86),
  ('expression -> expression XOR expression','expression',3,'p_expression_binop','booleanParser.py',87),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','booleanParser.py',97),
  ('expression -> NAME','expression',1,'p_expression_name','booleanParser.py',102),
  ('expression -> TRUE','expression',1,'p_expression_bool','booleanParser.py',111),
  ('expression -> FALSE','expression',1,'p_expression_bool','booleanParser.py',112),
]
